# Generated by Django 5.0.6 on 2024-06-28 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="New_review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=50, verbose_name="Название фильма"),
                ),
                (
                    "short_description",
                    models.CharField(
                        max_length=200, verbose_name="Краткое описание фильма"
                    ),
                ),
                ("text", models.TextField(verbose_name="Отзыв")),
                ("pub_date", models.DateTimeField(verbose_name="Дата публикации")),
            ],
            options={"verbose_name": "Отзыв", "verbose_name_plural": "Отзывы",},
        ),
    ]
